# Generated by Django 3.1.7 on 2021-06-06 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customersubscription_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=200, primary_key=True, serialize=False),
        ),
    ]
